name: 'New Relic Custom Event Action'
author: 'Pier Digital Services'
description: 'Send custom events to New Relic'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  eventType:
    description: 'Event Type inside New Relic. This will be used to query this data later.'
    required: false
    default: 'deploy'
  insightsInsertKey:
    description: 'Your New Relic Insights Insert Key.'
    required: true
  newrelicAccountId:
    description: 'New Relic Account ID.'
    required: true
  deploymentStatus:
    description: 'The status of the deployment to be sent to New Relic.'
    required: false
    default: '${{ job.status }}'
  description:
    description: 'Deployment description.'
    required: false
    default: '${{ github.event.commits[0].message }}'
  actor:
    description: 'The deployment actor.'
    required: false
    default: '${{ github.actor }}'
  project:
    description: 'The deployment project.'
    required: false
    default: '${{ github.repository }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    EVENT_TYPE: ${{ inputs.eventType }}
    DEPLOYMENT_STATUS: ${{ inputs.deploymentStatus }}
    DESCRIPTION: ${{ inputs.description }}
    ACTOR: ${{ inputs.actor }}
    PROJECT: ${{ inputs.project }}
    NEW_RELIC_INGIGHTS_INSERT_KEY: ${{ inputs.insightsInsertKey }}
    NEWRELIC_ACCOUNT_ID: ${{ inputs.newrelicAccountId }}
